### ISSUE TITLE
Questions about signal processing when modifing your code for AWR1642-ODS

### ISSUE THREAD

**Issue by zzwei1** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#1]
Hi, I'm processing data of AWR1642-ODS,which has an 'L' shape virtual array.

I wonna modify your code for AWR1642-ODS, and I think the only different thing is anle estimation, beacause AWR1642 has a linear virtual array, while AWR1642-ODS has an 'L'-shape virtual array.

However, when I check your code, I get confusion results after 2D-FFT(e.g., after range-FFT and angle-FFT). I use 'pms1000_30fs.mat' for test, and the target range is about 7m.
![image](https://user-images.githubusercontent.com/49705380/122962112-a8d5ec80-d3b7-11eb-8ab2-f2fdbd93afb1.png)
However, when I make a figure about 'Dopdata_sum' in your code (e.g. radar data cube after 2D-FFT, and now we have got both range and velocity estimation), I get the folloeing result, x-axis is range, and y-axis is Doppler velocity,
![image](https://user-images.githubusercontent.com/49705380/122962554-1f72ea00-d3b8-11eb-93f5-eb7d753717f5.png)
I can't find the target at range 7m.

Could you help me explain this result?
thanks in advance!

**Comment by Xiangyu-Gao** [comment]
Hi,

First, in your plot, the x-axis is Doppler while the y-axis is range. You can also use a suitable scale to visualize the target at 7m more clearly.
I have updated this repo by adding the range-Doppler image. Please check it if you are interested in it. Thanks!

**Comment by zzwei1** [comment]
> Hi,
> 
> First, in your plot, the x-axis is Doppler while the y-axis is range. You can also use a suitable scale to visualize the target at 7m more clearly.
> I have updated this repo by adding the range-Doppler image. Please check it if you are interested in it. Thanks!

Sorry for the late reply. Thanks very much ! I have figured above question out with your help!

By the way, do you have the workflow code about processing AWR1642-ODS or AWR1843 which has an equivalent L-shape antenna array, cause I notice that you mensioned that, "this script is used for processing the raw data collectd by TI awr1843" in the comments of 'generate_ra_3dfft.m' ? I want to learn about it.

I'm not sure about my results when I processing data from AWR1642-ODS, espetially when I estimate the elevation angle and azimuth angle.

**Comment by Xiangyu-Gao** [comment]
Sorry I don't have any codes available for processing the L-shape arrays. In that case, you might need to update current codes by adding one more elevation dimension to utilize the L-shape arrays.

**Comment by zzwei1** [comment]
> Sorry I don't have any codes available for processing the L-shape arrays. In that case, you might need to update current codes by adding one more elevation dimension to utilize the L-shape arrays.

Thanks a lot! I'll try it.
