### ISSUE TITLE
1. Why considering both "Rangedata_odd", "Rangedata_even" for Range-Angle Plot, but considering only "Rangedata_odd" for Range-Dopper plot?

### ISSUE THREAD

**Issue by PalgunaGopireddy** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#12]
I do not understand why only ``Rangedata_odd`` (Range estimated data of Tx1) is considered on which Velocity FFT is performed for plotting Range-Velocity (Also called Range-Doppler) image. 

But considered both the transmitters Range-estimated data i.e. ``Rangedata_odd``, ``Rangedata_even``, on which Angle FFT is performed for plotting Range-Angle Image.

In the paper it is told that the "a fast Fourier transform in the spatial dimension across RX elements (Angle FFT) resolves objects according to their arrival angles in azimuth". Then why consider the Range-estimated data due to both the Tx. 

I used `bms1000_30fs.mat` data
 I used only "Rangedata_odd" data for plot. It appears it has more widened along the angle axis comapred to the original.
![Rangedata_odd only used for RA plot](https://user-images.githubusercontent.com/106730853/225524513-b3da751a-7715-4726-aa73-5b7a05d52670.png)

I used both "Rangedata_odd", "Rangedata_even" for RD plot. I see no difference in the plot when did "Rangedata_odd" is only considered.
![Rangedata_odd, Rangedata_even both used for RD plot](https://user-images.githubusercontent.com/106730853/225524661-b5089f0b-d32e-41a0-9ac8-d8814e4932f1.png)

**Comment by Xiangyu-Gao** [comment]
Odd here means all chirps for Tx1 and even means all chirps for Tx2, you don’t want to mix the chirps of two antennas for Doppler estimation since the phase of two Tx is different when your doa is not zero.

**Comment by PalgunaGopireddy** [comment]
What's doa?

**Comment by Xiangyu-Gao** [comment]
For RA plot, we use two Txs and 4 Rxs to form the MIMO array to improve the angle resolution. Therefore we consider both Tx Range Compensated Data.

**Comment by PalgunaGopireddy** [comment]
Thank you Gao.
