### ISSUE TITLE
Does Range-Angle Plot and Range-Azimuth Plot both not same?

### ISSUE THREAD

**Issue by PalgunaGopireddy** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#13]
This paper shows the ``Range-Angle Plot``. It is obtained by applying ``Angle FFT`` on Range compensated data. As in the code the Angle FFT is applied on the 2nd dimesnion of the data variable `Rangedata_merge` (8 points), which indicated the [4 Rx samples from Tx1, 4Rx samples from T2].

1) Does both the ``Range-Angle Plot``, and the ``Range-Azimuth`` plot both same? If not, How to obtain the ``Range-Azimuth`` plot.

2) ``Velocity FFT`` is applied on the chirps. Which is 3rd dimension of `Rangedata_merge` for obtaining RD plot. Does that mean the third dimension is already in special domain.

**Comment by Xiangyu-Gao** [comment]
They are same.

**Comment by PalgunaGopireddy** [comment]
I know that ``Angle FFT`` resolves objects according to their arrival angles in azimuth.

So, if I use 1Tx for 1Rx, then Performing `Range FFT` without Angle FFT gives Range-Azimuth Plot ?
    (or) should I also perform ``Angle FFT`` on the 2nd dimension (1 point), then squeeze the 3rd dimension for this also for 
          getting Range-Azimuth plot?

**Comment by Xiangyu-Gao** [comment]
Under the 1Tx case, you need at least two Rx antennas for doing the angle estimation, otherwise, the object cannot be resolved by angle. If you have more than 2 Rx antennas, you can perform Angle FFT on the Rx antenna dimension, then squeeze the 3rd dimension.

**Comment by PalgunaGopireddy** [comment]
Thank you Gao
