### ISSUE TITLE
Questions about clustering function

### ISSUE THREAD

**Issue by Timothy-105** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#2]
Hi,thanks for your coding! I have a question about clustering function.
clustering(save_det_data,fft_Vel,veloc_bin_norm,dis_thrs,rng_grid,agl_grid)
what does the veloc_bin_norm mean? Is the length of save_det_data(:,2)?

**Comment by Xiangyu-Gao** [comment]
The veloc_bin_norm parameter is for normalizing the velocity bin index to the same level of the index range/angle bin.
