### ISSUE TITLE
About neural networks

### ISSUE THREAD

**Issue by QM1412** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#21]
Hello author, let me ask, why do you need to use stft, and then the data in the .mat, is it just the data collected by radar, or is the author's .mat generated by something else, I've been working on this thing recently, and then do you need to use the camera part in this code?

**Comment by Xiangyu-Gao** [comment]
The stft is to generate the micro-Doppler signatures for classification. The .mat file are converted from the data we collected by radar. We use .mat as it is easy to parse.

**Comment by QM1412** [comment]
I also want to ask a question, that is, I also use 1843 to collect data, the measurement is static sitting, but the number of point clouds obtained is very small, do I need to combine anything to identify the sitting posture, you should measure the movement, although you can get more point clouds by improving the false alarm rate, but this can not distinguish what is the environment, what is the human body, can you give me a little direction and suggestions?

**Comment by Xiangyu-Gao** [comment]
It is normal to have fewer points for imaging the static objects. You may want to use a better AoA / imaging algorithm, e.g., MUSIC, SAR, etc to enhance the radar performance. By accumulating the point clouds across time can also boost the number of points.

**Comment by QM1412** [comment]
Okay, thanks for the suggestion
