### ISSUE TITLE
Problem about sample and rangebin。

### ISSUE THREAD

**Issue by hujinxiangwd** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#22]
sample = 128. why use fft_Rang = 134 to range-fft ?
if use fft_Rang=128
![image](https://github.com/Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification/assets/73588372/b911b8d8-29f5-4e5c-9476-a2b6aa92df6d)
but when use fft_Rang=134
![image](https://github.com/Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification/assets/73588372/bf0651c5-8bca-42d6-bc84-f9875415d599)
they have different mirco Doppler map
thank you for your reply

**Comment by Xiangyu-Gao** [comment]
Yes, we use 134 points for Range FFT first and then remove the first 3 and last 3 bins to eliminate self-leakage effects (the transmit signal is directly received on board). So if you delete the code for removing the first 3 and last 3 bins after Range FFT, you can use 128 points FFT.
