### ISSUE TITLE
Question about understanding the code.  what does `peakGrouping.m` do? and the STFT parameters in `generate_microdoppler_stft.m`

### ISSUE THREAD

**Issue by PalgunaGopireddy** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#23]
**1. What does `peakGrouping.m` do?**
 I undersatnd that the detected point clouds are obtained using `cfar_RV.m`. The output of `cfar_RV.m` is sent to `peakGrouping.m`. The output of `peakGrouping.m` (detout) is a subset of output of `cfar_RV.m`.
Why take subset of the point clouds location detected in `cfar_RV.m` not all point clouds? How `peakGrouping.m` determines this subset of piont clouds?

**2. Does the values of STFT parameters `Lr`, `La` etc are same for each image?**
From the code, I understand that the `Lr`,` La` values denotes the number of _range and angle bins_ to be chosen for radar data cube(Fig. 9, Fig. 10 of paper) .
My question is, since the targets can be present in any range and angle bins, how can these values be the same for each input raw data?

**Comment by Xiangyu-Gao** [comment]
peakGrouping.m is for clustering, i.e., grouping nearby points
`Lr`,` La` etc are the same for each image. We choose sufficient large `Lr`, and` La`  values to accommodate targets at different locations.

**Comment by PalgunaGopireddy** [comment]
Ok. Thanks
 So for a dataset with multiple samples, we should choose the the range of bins a target occupies, then using the 'for loop' we detect centre bins of the target 'center_r', and 'center_a' and crop the RA image using  `Angdata_crop(center_r-(Lr-1)/2:center_r+(Lr-1)/2,center_a-(max(Ang_seq)/2+1)+Ang_seq   ,:)`

I don't understand why use maximum value of  `Ang_seq`  (_dilated angle bin index for cropping)_ instead of using `La`?

**Comment by Xiangyu-Gao** [comment]
1) Why dilated angle bin index for cropping:
This is a good question. Because the angular resolution is limited most of the consecutive angle bins belong to the same peak or beam. We use dilated angle bins to cover larger angle coverage.
2) The Doppler velocity can be measured for radial velocity change only. So microdoppler signatures should also represent change in movement in range direction only right.
Your statement is correct.
