### ISSUE TITLE
Question about phase compensation

### ISSUE THREAD

**Issue by hujinxiangwd** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#25]
![)2 D(@N EYFIEP1GH~TCZ6](https://github.com/Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification/assets/73588372/ca37ccb2-98ed-4e32-bd87-1f9a9ac92740)
why using phase compenation twice ?
![TBIQL8PR)L}KQ@(H53MHOVT](https://github.com/Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification/assets/73588372/3019dcf8-434d-4036-9d9f-5554bf1f58cb)

**Comment by Xiangyu-Gao** [comment]
The first compensation is for RangeData and the second compensation is for DopplerData and both of them were not compensated.

**Comment by hujinxiangwd** [comment]
> The first compensation is for RangeData and the second compensation is for DopplerData and both of them were not compensated.
in equation pha_com = exp(-1i * pi *...)
Why use pi instead of  2*pi ?

**Comment by Xiangyu-Gao** [comment]
the compensation equation originally should be: pha_com = exp(-1i * 2 pi * (detout(1,pick_idx)-fft_Vel/2-1) / fft_Vel / 2.)
2 is canceled out in the equation
