### ISSUE TITLE
测试生成的微多普勒数据

### ISSUE THREAD

**Issue by hujinxiangwd** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#26]
![image](https://github.com/Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification/assets/73588372/2e9c1ed8-a69b-4110-b6e9-5e0eb70ee2cf)
我使用2019_04_09_bms1000文件夹中cylist的数据生成STFT_data，并放入\template data\test_data_part\2019_05_28\2019_05_28_bm1s011进行测试，无法识别为cylist。
![image](https://github.com/Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification/assets/73588372/bd027aa5-c572-427a-80d2-0a0b74765c3e)
这是部分多普勒图结果。不知道哪里出了些问题
非常感谢您的指导与回复！
我又测试了行人和车辆，他们是可以分辨的。
0-15是cylist，其余为行人和车辆。
![image](https://github.com/Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification/assets/73588372/c895d6e3-75d8-4bdb-9717-6fa0f86a2929)

**Comment by Xiangyu-Gao** [comment]
2019_04_09_bms1000的数据是用于training set的， 我没把它做过testing所以不太清楚结果应该是怎样的。另外，生成的stft图片中间有很多白色条纹有点奇怪。
