### ISSUE TITLE
why STFT_data(:,:,(1+Lr*La)/2) is result?

### ISSUE THREAD

**Issue by zz2026sd** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#27]
May I ask why STFT_data(:,:,(1+Lr*La)/2) is selected for the final drawing? If so, what is the purpose of crop?

**Comment by Xiangyu-Gao** [comment]
Is it just for visualization?

**Comment by Chenweimin-Zou** [comment]
Thank you for your reply, if I want to get the micro-Doppler information of the whole person (displayed on a graph), do I need to stft each point in the cropped area and then add them together?

**Comment by Xiangyu-Gao** [comment]
yes I think what you mentioned is correct
