### ISSUE TITLE
not understanding the use of 'num_filter' and 'ord_stat' in "cfar_ca1D_square.m"

### ISSUE THREAD

**Issue by PalgunaGopireddy** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#28]
Hi.
I went through the `cfar_ca1D_square.m` algorithm used for `doppler_sum` of size (256,128)
I checked how the `cfar_ca1D_square.m` works by sending the 128 azimuth samples, corresponding to the first range bin (i.e. `doppler_sum(1,:)`), noiseWin = 4, guardLen = 7

For `wrapMode = 0`, I checked the window indices used by each azimuth bin. Here is the screenshot showing the indices considered for calculating the noise estimate of each of the 128 bins.
![image](https://github.com/user-attachments/assets/7e3c4d27-1bf7-4515-834c-711c2d66ed10)

I understand the left and right windows being used for middle indices, the right window for starting indices, and the left window for ending indices based on the noiseWin , guardLen.

But I am unbale to understand the use of `ord_stat =0.7` to cancel out some elements form the windows used for  noise calculation. Why are some elements removed? As far as I know all the eliments in the window should be considered. Using which theory this CFAR-CA algorithm is prepared.
It is also written in one of the comments as `% if not CAOS-CFAR, set ord_stat = 1`. But `CAOS-CFAR` algorithm finds the minimim of the noise estimate from left and right indices. Why putting `ord_stat ~= 1` makes it `CAOS-CFAR`

**Comment by Xiangyu-Gao** [comment]
`ord_stat` is a parameter and you can set it to 1 to disable the window filtering, e.g., use all cells from the left and right indices.

**Comment by PalgunaGopireddy** [comment]
Thanks I understood that. I was just wondering why do that. I never saw a CFAR window selection like this. If it's just a thing you tried, never mind asking this question.
I also saw the comment `% if not CAOS-CFAR, set ord_stat = 1`. But in CAOS-CFAR we select the minimum of the left, right window values. 

Thanks.

**Comment by Xiangyu-Gao** [comment]
CAOS-CFAR is a public method https://www.radartutorial.eu/01.basics/False%20Alarm%20Rate.en.html#:~:text=CAOS%2DCFAR%20or%20OS%2DCFAR
