### ISSUE TITLE
Input data

### ISSUE THREAD

**Issue by Srivatsa1648** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#29]
How is pms1000_30fs.mat file is created from raw radar adc data of each frame which is in .mat file? Can u provide any code for this

**Comment by newradar1** [comment]
Hey did you figure this out? I'm also having an issue

**Comment by Srivatsa1648** [comment]
> Hey did you figure this out? I'm also having an issue

No

**Comment by Xiangyu-Gao** [comment]
please check this discussion https://github.com/Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification/issues/17#issuecomment-2292868885

**Comment by Srivatsa1648** [comment]
> please check this discussion [#17 (comment)](https://github.com/Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification/issues/17#issuecomment-2292868885)

Thank you for your reply it worked for me
