### ISSUE TITLE
questions about phase compensation for virtual elements

### ISSUE THREAD

**Issue by wilson2015** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#3]
i‘m confusing about the theory behind that ?
pha_comp_term = exp(-1i*pi*detout(1,pick_idx)-fft_vel/2-1)/fft_vel);

**Comment by Xiangyu-Gao** [comment]
This is to compensate for the phase shift of TDM MIMO caused by the additional target movement during the interval between two transmitters sending waves. More details are in described in paper https://arxiv.org/abs/2101.09293 section II.B
