### ISSUE TITLE
Explanation of 2nd step from Read me File  

### ISSUE THREAD

**Issue by hpaul96** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#4]
<img width="790" alt="error_fft_range_script" src="https://user-images.githubusercontent.com/47212447/171336704-02b83d0d-63d2-45db-b93f-c456349c27ec.png">
<img width="793" alt="Error_microdopller_script" src="https://user-images.githubusercontent.com/47212447/171336713-3907cb29-1ea3-4ce5-a2f9-f9a73f9c16d0.png">

As per file "Read me" in the "Run codes for generating micro-Doppler maps" section. I am getting an error in the 2nd step i.e to run generate_microdoppler_stft.m file. 

The error says "Unrecognized function or variable 'hanning'.". the function was found in fft script (in fft modules) there is also the same error showing.

I have pasted a screenshots

Can you help me in resolving the issue?

**Comment by Xiangyu-Gao** [comment]
"hanning" function belongs to Matlab signal processing toolbox. If your matlab does not have this toolbox, you will get this error.
