### ISSUE TITLE
.bin data size problem

### ISSUE THREAD

**Issue by swin223** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#5]
Hi, thank you very much for providing the bin file, I first calculated the bin size according to the parameters of the radar configuration in your paper ("Number of chirps in one frame 255; Number of samples of one chirp 128; Number of transmitters, receivers 2, 4") and calculated the file size by the TI provided, the bin size was calculated as 940,032,000 bytes, while the bin file size you provided was 947,044,432 bytes, I don't know why the size is different, which makes the configuration of the parameters of the code when I extract the first 30 frames a problem. Thank you for your reply.

**Comment by Xiangyu-Gao** [comment]
I believe the binary file has zero padding at the end or beginning of the file. and this is the issue from ti board. You can find a script we used for reading the binary file named 'readDCA1000.m' under the 'modules' folder.

**Comment by Xiangyu-Gao** [comment]
This binary file has some issues after compression. I have updated a new binary file named '2019_04_30_pbms002_raw_900fs' and a script 'read_bin.m' for reading it.
