### ISSUE TITLE
Contents of .mat files

### ISSUE THREAD

**Issue by atulpant** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#6]
Hello Xiangyu-Gao,

I was going through the paper along with the codes. I haven't finished up reading the paper but while going through the data from FMCW I had a question related to it.
When I try to view the contents of .mat files I know it is a dictionary with arrays as one of the following values. After looking at those array values it seems they are mixed characters (not specifically integer or float).
Example :-
[-127.-17.j  -63.-13.j  -34. +3.j ...  -10.-14.j  -10. +8.j  -26. +2.j]
 [  81. +3.j   73. +6.j   69.+25.j ...    4. +5.j    3.+23.j  -17.+11.j]
 [-129.+68.j  -73.+43.j  -62.+56.j ...    2. +0.j    2.+23.j  -16.+18.j]
 
 Keeping in mind you have knowledge about FMCW after working on it, can you explain what is the output format from FMCW and why the array has mixed characters?

**Comment by Xiangyu-Gao** [comment]
Thanks for reaching out. The data format is the complex number so when you see for example -127.-17.j.  It means a complex number with real part -127.000000 and imag part -17.000000. Note that I keep each part as float double format.

Hope this helps.

Xiangyu
