### ISSUE TITLE
Conversion of .bin to .mat?

### ISSUE THREAD

**Issue by atulpant** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#7]
Hello Xiangyu,

You have provided with the .bin file which contains all the information taken from the radar. I tried reading it using the code given and it works. My question after that is that how you are converting the .bin into .mat format because .mat is the input to the main pipeline. Also, there is one .bin file but 3 .mat file, are all those 3 derived from single file or 3 different files?

**Comment by Xiangyu-Gao** [comment]
Hi, a script for reading binary file is contained in this repo called "read_bin.m" that converts the .bin file to .mat file. The provided .bin file is just sample data, not the root data of three 3.mat files.

**Comment by atulpant** [comment]
Okay, thanks for your support.
