### ISSUE TITLE
Real and imaginary part for analysis

### ISSUE THREAD

**Issue by atulpant** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#8]
Hi Xiangyu,

I wanted to enquire about the real and imaginary values which we get after FFT.

After performing FFT on the raw data we get a complex number comprising of real and imaginary part. It is technically a frequency domain. Going through different reading materials it is mentioned that we can derive the amplitude and phase from the complex number which can be further used for the analysis.
My question is can we use the raw real and imaginary values which is obtained after FFT for any analysis such as clustering, classification etc.

**Comment by Xiangyu-Gao** [comment]
Of course, you can use the real and image values for doing some analysis such as classification. In our paper "[RAMP-CNN: A Novel Neural Network for Enhanced Automotive Radar Object Recognition](https://arxiv.org/pdf/2011.08981.pdf)", we use the real/imag values of range-angle images for object recognition using Deep learning networks. The DL networks can figure out inherently what formates the real/imag values can be converted to for recognition, not limited to the amplitude/phase.
