### ISSUE TITLE
radar config parameters

### ISSUE THREAD

**Issue by laksmikanth** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#9]
fft range parameter 134 is used instead of 128, any design reason behind this
params.fft_Rang = 134; % 134=>128

**Comment by Xiangyu-Gao** [comment]
Yes, we use 134 points FFT first and then remove the first 3 and last 3 points for eliminating the effects of self-leakage (the transmit signal is directly received on board).
